Updated GitHub Actions workflow for testing

diff --git a/.github/workflows/ga-validate-packer.yml b/.github/workflows/ga-validate-packer.yml
--- a/.github/workflows/ga-validate-packer.yml
+++ b/.github/workflows/ga-validate-packer.yml
@@ -45,36 +45,36 @@ jobs:
               if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
                 missing_secrets+=("AWS_SECRET_ACCESS_KEY")
               fi
-              if [ -z "${{ secrets.DB_NAME }}" ]; then
-                missing_secrets+=("DB_NAME")
-              fi
-              if [ -z "${{ secrets.DB_USER }}" ]; then
-                missing_secrets+=("DB_USER")
-              fi
-              if [ -z "${{ secrets.DB_PASSWORD }}" ]; then
-                missing_secrets+=("DB_PASSWORD")
-              fi
               if [ -z "${{ secrets.VPC_ID }}" ]; then
-                missing_secrets+=("VPC_ID")
+              missing_secrets+=("VPC_ID")
               fi
               if [ -z "${{ secrets.SUBNET_ID }}" ]; then
-                missing_secrets+=("SUBNET_ID")
+              missing_secrets+=("SUBNET_ID")
               fi
               if [ -z "${{ secrets.AWS_REGION }}" ]; then
-                missing_secrets+=("AWS_REGION")
+              missing_secrets+=("AWS_REGION")
               fi
               if [ -z "${{ secrets.DEMO_USER }}" ]; then
-                missing_secrets+=("DEMO_USER")
-              fi
-              if [ -z "${{ secrets.GCP_PROJECT_ID }}" ]; then
-                missing_secrets+=("GCP_PROJECT_ID")
+              missing_secrets+=("DEMO_USER")
               fi
               
               if [ ${#missing_secrets[@]} -ne 0 ]; then
-                echo "Error: The following secrets are not set:"
-                printf '%s\n' "${missing_secrets[@]}"
-                exit 1
+              echo "Error: The following secrets are not set:"
+              printf '%s\n' "${missing_secrets[@]}"
+              exit 1
               fi
+            # if [ -z "${{ secrets.DB_NAME }}" ]; then
+            #   missing_secrets+=("DB_NAME")
+            # fi
+            # if [ -z "${{ secrets.DB_USER }}" ]; then
+            #   missing_secrets+=("DB_USER")
+            # fi
+            # if [ -z "${{ secrets.DB_PASSWORD }}" ]; then
+            #   missing_secrets+=("DB_PASSWORD")
+            # fi
+              # if [ -z "${{ secrets.GCP_PROJECT_ID }}" ]; then
+            #   missing_secrets+=("GCP_PROJECT_ID")
+            # fi
           
           - name: Packer init
             working-directory: ./packer
@@ -86,7 +86,7 @@ jobs:
             env:
               AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
               AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-              GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
+              # GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
             run: |
               # Create a zip file for validation purposes
               cd ..
@@ -94,13 +94,13 @@ jobs:
               cd packer
               
               packer validate \
-                -var "db_password=${{ secrets.DB_PASSWORD }}" \
-                -var "db_name=${{ secrets.DB_NAME }}" \
-                -var "db_user=${{ secrets.DB_USER }}" \
-                -var "vpc_id=${{ secrets.VPC_ID }}" \
-                -var "subnet_id=${{ secrets.SUBNET_ID }}" \
-                -var "aws_region=${{ secrets.AWS_REGION }}" \
-                -var "demo_user=${{ secrets.DEMO_USER }}" \
-                -var "gcp_project_id=${{ secrets.GCP_PROJECT_ID }}" \
-                .
-            continue-on-error: false
+              -var "vpc_id=${{ secrets.VPC_ID }}" \
+              -var "subnet_id=${{ secrets.SUBNET_ID }}" \
+              -var "aws_region=${{ secrets.AWS_REGION }}" \
+              -var "demo_user=${{ secrets.DEMO_USER }}" \
+              .
+              continue-on-error: false
+            # -var "db_password=${{ secrets.DB_PASSWORD }}" \
+            # -var "db_name=${{ secrets.DB_NAME }}" \
+            # -var "db_user=${{ secrets.DB_USER }}" \
+            # -var "gcp_project_id=${{ secrets.GCP_PROJECT_ID }}" \
