Updated GitHub Actions workflow for testing

diff --git a/.github/workflows/ga-validate-packer.yml b/.github/workflows/ga-validate-packer.yml
--- a/.github/workflows/ga-validate-packer.yml
+++ b/.github/workflows/ga-validate-packer.yml
@@ -46,22 +46,22 @@ jobs:
                 missing_secrets+=("AWS_SECRET_ACCESS_KEY")
               fi
               if [ -z "${{ secrets.VPC_ID }}" ]; then
-              missing_secrets+=("VPC_ID")
+                missing_secrets+=("VPC_ID")
               fi
               if [ -z "${{ secrets.SUBNET_ID }}" ]; then
-              missing_secrets+=("SUBNET_ID")
+                missing_secrets+=("SUBNET_ID")
               fi
               if [ -z "${{ secrets.AWS_REGION }}" ]; then
-              missing_secrets+=("AWS_REGION")
+                missing_secrets+=("AWS_REGION")
               fi
               if [ -z "${{ secrets.DEMO_USER }}" ]; then
-              missing_secrets+=("DEMO_USER")
+                missing_secrets+=("DEMO_USER")
               fi
               
               if [ ${#missing_secrets[@]} -ne 0 ]; then
-              echo "Error: The following secrets are not set:"
-              printf '%s\n' "${missing_secrets[@]}"
-              exit 1
+                echo "Error: The following secrets are not set:"
+                printf '%s\n' "${missing_secrets[@]}"
+                exit 1
               fi
             # if [ -z "${{ secrets.DB_NAME }}" ]; then
             #   missing_secrets+=("DB_NAME")
